server:
  port: 8844
spring:
  application:
    name: spring-zuul
eureka:
  instance:
    preferIpAddress: true
    #这样写eureka服务注册中心会显示本机ip+端口号啊
    instanceId: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.9.129:1111/eureka/
zuul:
  routes:
    eagle-api: /eagle/**


